### ISSUE TITLE
Trouble accessing package object definitions from within Java

### ISSUE THREAD

**Issue by bherd-rb** [EconomicSL/auctions#19]
@davidrpugh I am having some trouble accessing the definitions within the package object from within Java. For example:

```scala
package object auctions {
   ...
   trait Tradable
   ...
}
```

I would like to use `Tradable` shown above to define a simple auction wrapper in Java. The code above compiles to a file `package$Tradable.class` which, I thought, I would be able to import into Java according to [that](http://stackoverflow.com/questions/26516361/using-vals-from-scala-package-object-in-java) post in a straightforward way, e.g. as follows. 

```java
public class JSimpleAuction<T extends org.economicsl.auctions.package$Tradable> { 
   ...
   public void plus(LimitAskOrder<T> order { auction.$plus(order); }
   ...
}
```
Unfortunately that doesn't work, `package$Tradable$` isn't recognised. [This](http://stackoverflow.com/questions/23170058/using-scala-class-defined-in-package-object-from-java) might be an explanation. 

 be possible to move the classes and traits out of the package object into the package itself in order to facilitate the interoperability?

**Comment by davidrpugh** [comment]
@bherd-rb Interesting!  Yes definitely.  Will submit a PR for this immediately. From the SO link it appears that I am slightly abusing the use case for package objects.
