### ISSUE TITLE
Simple test auction class with clearing function

### ISSUE THREAD

**Issue by bherd-rb** [EconomicSL/auctions#21]
@davidrpugh I am currently adapting my Java auction wrapper to the changes in the repo. For testing purposes, I have implemented a simple auction class that provides a clearing function. However I'm unsure about which actions I need to perform and in what order. This is what I'm currently doing:  

```scala
class SimpleAuction[T <: Tradable] {
   var orderBook = FourHeapOrderBook.empty[T]
   ...
   def clear[P <: PricingRule[T, Price]](p : P) = {
      val price = p(orderBook)
      val (pairedOrders, orderBook_new) = orderBook.takeWhileMatched
      orderBook = orderBook_new
      (price, pairedOrders.toList) 
   }
   ...
}
```

Does that make sense?! For now, it doesn't have to be perfect or efficient at all.

**Comment by davidrpugh** [comment]
@bherd-rb Definitely on the right track. Your question is related to PR #5 where I am thinking about similar issues.  I would make some minor modifications...

```scala
class SimpleAuction[T <: Tradable] {

  // need to think about concurrency...potentially multiple threads will have access to the same SimpleAuction instance...
  private[this} var orderBook = FourHeapOrderBook.empty[T]
  ...

  // return type of the clear method is debatable (i.e., could be Queue, Stream, List, ???)
  def clear[P <: PricingRule[T, Price]](p : P): Option[Stream[Fill[T]]] = {
    p(orderBook)  match {
      case Some(price) => // p returns an Option[Price]!
        val (pairedOrders, newOrderBook) = orderBook.takeWhileMatched
        orderBook = newOrderBook // SIDE EFFECT!
        pairedOrders.map( (askOrder, bidOrder) => Fill(askOrder, bidOrder, price))
      case None => None
    }
  }
   ...
}
``` 

BTW I really like your idea to parameterize the `clear` method! Seems like it would allow for more flexible auction implementations.  One could potentially switch pricing rules dynamically at run-time.  I would never had thought of that...

In my mind the major outstanding design questions for simply auction implementation is whether of not auctions should be mutable or immutable.  An immutable implementation of the above would be...

```scala
class DoubleAuction[T <: Tradable] private(orderBook: FourHeapOrderBook[T]) {

  def insert(order: LimitAskOrder[T]): DoubleAuction = {
    new DoubleAuction(orderBook + order)
  }

  def insert(order: LimitBidOrder[T]): DoubleAuction = {
    new DoubleAuction(orderBook + order)
  } 

  def remove(order: LimitAskOrder[T]): DoubleAuction = {
    new DoubleAuction(orderBook - order)
  }

  def remove(order: LimitBidOrder[T]): DoubleAuction = {
    new DoubleAuction(orderBook - order)
  }

  def clear(p: PricingRule[T, Price]]): (Option[Stream[Fill[T]]], DoubleAuction[T]) = {
    p(orderBook) match {
      case Some(price) => 
        val (pairedOrders, newOrderBook) = orderBook.takeWhileMatched
        val fills = pairedOrders.map( (askOrder, bidOrder) => Fill(askOrder, bidOrder, price))
        (Some(fills), new DoubleAuction(newOrderBook))
      case None => (None, orderBook)
  }
  
}

object DoubleAuction {

  def withEmptyOrderBook[T <: Tradable]: DoubleAuction[T] = {
    new DoubleAuction(FourHeapOrderBook.empty[T])
   }

}
```  
I am not quite sure whether or not the above will compile or not.  Thoughts? @rafabap do you have a strong opinion?

**Comment by davidrpugh** [comment]
@bherd-rb and @rafabap I have just pushed an implementation of the above immutable `DoubleAuction` to the open PR #5 for discussion.

**Comment by bherd-rb** [comment]
@davidrpugh Cool, thanks. I'll give that solution a try. My intuitive feeling is that an immutable implementation is better. It is certainly more consistent since everything else is also immutable. On the other hand, it is probably less efficient because a new auction object is created every time the order book changes. 

We could start with an immutable implementation as our preferred solution but allow for mutable variants (e.g. via a new sub-package `mutable`) in case someone has particular requirements w.r.t. efficiency .

**Comment by davidrpugh** [comment]
@bherd-rb having a `mutable` sub-package was the approach that I took with `agora`.  I expect your intuition is correct regarding relative efficiency of immutable vs mutable implementations.

In `agora` I had both immutable and mutable implementations of order books which then led to mutable vs immutable implementations of auction, etc.  Perhaps this is something that should be demand drive? For now we move forward with an immutable design and then think about mutability when we have actual data on efficiency (or lack thereof of our immutable implementation).

**Comment by bherd-rb** [comment]
@davidrpugh Yes, sounds good.
