### ISSUE TITLE
Publishing machinery

### ISSUE THREAD

**Issue by davidrpugh** [EconomicSL/auctions#47]
Need to setup the machinery to publish new releases of the relevant artifacts.  Where should we publish to Maven? Somewhere else? @bherd-rb where do you pull dependencies from?

Ideally I want to set up a cron job that will automatically publish the contents of the develop branch to some online artifact repository at midnight UTC.  For the immediate future I will handle publishing merging develop branch into master and then publishing stable releases on a more or less monthly timeline.

**Comment by davidrpugh** [comment]
Looks like [Travis CI][(https://docs.travis-ci.com/user/cron-jobs/) already supports daily, weekly, monthly cron jobs as a beta feature.  @herculesl should enable cron jobs for the auctions repo and then add relevant instructions to publish the code to the `.travis.yml` file and then make sure that these instructions only get executed when the `TRAVIS_EVENT_TYPE` environment variable for that build has the value `cron`.

Details regarding publishing via SBT can be found [here](http://www.scala-sbt.org/0.13/docs/Publishing.html).  Looks like @herculesl will need to generate some kind of encrypted credentials in order to publish the cron job for us...

**Comment by herculesl** [comment]
I have initiated daily cron jobs for the develop branch; I also went ahead and enabled auto-cancel of jobs which automatically cancels build jobs that are not using the most up to date code.

**Comment by davidrpugh** [comment]
@bherd-rb How are you currently publishing the .jar files for use in your simulator? Are you publishing to a local internal repo? Would you be able to pull down .jar files and other relevant artifacts if I published them to Maven or Sonatype?

**Comment by herculesl** [comment]
Publication machinery for daily snapshots looks to be sorted by PRs #56 and #62. Still need to sort out publication machinery for official releases.  This will need to be done once the `0.1.0` feature branch has been created off of `develop` in preparation for merging to `master`.
